# Generated by Django 4.1.2 on 2023-02-10 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='isofficial',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
