# Generated by Django 4.1.2 on 2023-02-10 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_article_isofficial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='forfinal',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='forfirst',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='forsecond',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='forthird',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
