# Generated by Django 4.1.2 on 2023-02-10 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
